server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
